---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: rye sync
      - name: Format
        run: rye format --check
      - name: Lint
        run: rye lint
